---
- name: "Directory for Backend"
  file:
    path: ~/backend
    state: directory

- name: "Unarchive the artifact"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend
    npm install

- name: "Node app and pm2"
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "pm2 is configured to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
    